[package]
name = "geo-pres"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.6", features = ["png", "jpeg", "webp"] }
regex = "1.11.1"
tokio = { version = "1.46.1", features = ["full"] }
